name: CI

on: [push, pull_request]

jobs:
  Cpp-Lint-WebKit:
      name: C++ lint
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      
      - uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source: 'src/'
          extensions: 'h,cpp'
          clangFormatVersion: 10
          style: WebKit

  flatpak:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:6
      options: --privileged

    steps:
    - uses: actions/checkout@v2

    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      with:
        bundle: ElementaryCpp.flatpak
        manifest-path: com.github.jeysonflores.elementarycpp.json

        run-tests: true

        repository-name: appcenter
        repository-url: https://flatpak.elementary.io/repo.flatpakrepo
        cache-key: "flatpak-builder-${{ github.sha }}"
